-- Amplía el catálogo CIE-10 con códigos comunes para la clínica (ginecología,
-- obstetricia, urinario/GU, general, pediatría). Idempotente y aditivo:
-- ON CONFLICT DO NOTHING no toca los que ya existen.
INSERT INTO "Cie10" ("codigo", "descripcion") VALUES
  -- Urinario / genitourinario
  ('N39.0', 'Infección de vías urinarias, sitio no especificado'),
  ('N30.0', 'Cistitis aguda'),
  ('N30.9', 'Cistitis, no especificada'),
  ('N34.1', 'Uretritis no específica'),
  ('N10', 'Nefritis tubulointersticial aguda (pielonefritis aguda)'),
  ('N23', 'Cólico renal, no especificado'),
  ('N20.0', 'Cálculo del riñón'),
  ('N20.1', 'Cálculo del uréter'),
  ('R30.0', 'Disuria'),
  ('R31', 'Hematuria, no especificada'),
  ('R35', 'Poliuria'),
  -- Ginecología
  ('N70.9', 'Salpingitis y ooforitis, no especificadas'),
  ('N71.9', 'Enfermedad inflamatoria del útero, no especificada'),
  ('N72', 'Enfermedad inflamatoria del cuello uterino'),
  ('N73.9', 'Enfermedad inflamatoria pélvica femenina, no especificada'),
  ('N76.0', 'Vaginitis aguda'),
  ('N76.1', 'Vaginitis subaguda y crónica'),
  ('N75.1', 'Absceso de la glándula de Bartholin'),
  ('N80.9', 'Endometriosis, no especificada'),
  ('N81.9', 'Prolapso genital femenino, no especificado'),
  ('N83.2', 'Otros quistes ováricos y los no especificados'),
  ('N84.1', 'Pólipo del cuello del útero'),
  ('N85.9', 'Trastorno no inflamatorio del útero, no especificado'),
  ('N87.9', 'Displasia del cuello uterino, no especificada'),
  ('N91.2', 'Amenorrea, no especificada'),
  ('N92.0', 'Menstruación excesiva y frecuente con ciclo regular'),
  ('N92.6', 'Menstruación irregular, no especificada'),
  ('N93.9', 'Hemorragia vaginal y uterina anormal, no especificada'),
  ('N94.4', 'Dismenorrea primaria'),
  ('N94.5', 'Dismenorrea secundaria'),
  ('N94.6', 'Dismenorrea, no especificada'),
  ('N95.0', 'Hemorragia posmenopáusica'),
  ('N95.1', 'Estados menopáusicos y climatéricos femeninos'),
  ('N97.9', 'Infertilidad femenina, no especificada'),
  -- Mama
  ('N61', 'Trastornos inflamatorios de la mama'),
  ('N63', 'Masa no especificada en la mama'),
  ('N60.1', 'Mastopatía quística difusa'),
  -- Infecciones genitales / ITS
  ('B37.3', 'Candidiasis de la vulva y de la vagina'),
  ('A59.0', 'Tricomoniasis urogenital'),
  ('A54.9', 'Infección gonocócica, no especificada'),
  ('A56.0', 'Infección del tracto genitourinario inferior por clamidias'),
  ('A63.0', 'Verrugas anogenitales (venéreas)'),
  ('A60.0', 'Infección de genitales por virus del herpes'),
  -- Embarazo / obstetricia
  ('Z32.1', 'Embarazo confirmado'),
  ('Z34.0', 'Supervisión de primer embarazo normal'),
  ('Z34.8', 'Supervisión de otros embarazos normales'),
  ('Z35.9', 'Supervisión de embarazo de alto riesgo, no especificada'),
  ('Z39.0', 'Atención y examen inmediatamente después del parto'),
  ('O10.9', 'Hipertensión preexistente no especificada que complica el embarazo'),
  ('O13', 'Hipertensión gestacional [inducida por el embarazo]'),
  ('O14.9', 'Preeclampsia, no especificada'),
  ('O21.0', 'Hiperémesis gravídica leve'),
  ('O24.4', 'Diabetes mellitus que se origina en el embarazo'),
  ('O20.0', 'Amenaza de aborto'),
  ('O03.9', 'Aborto espontáneo, completo o no especificado, sin complicación'),
  ('O99.0', 'Anemia que complica el embarazo, el parto y el puerperio'),
  -- Anticoncepción / tamizaje
  ('Z30.0', 'Consejo general sobre la anticoncepción'),
  ('Z30.1', 'Inserción de dispositivo anticonceptivo (DIU)'),
  ('Z12.4', 'Examen de pesquisa especial para neoplasia del cuello uterino'),
  ('Z12.3', 'Examen de pesquisa especial para neoplasia de mama'),
  -- Endocrino / metabólico
  ('E10.9', 'Diabetes mellitus tipo 1, sin complicaciones'),
  ('E03.9', 'Hipotiroidismo, no especificado'),
  ('E05.9', 'Tirotoxicosis [hipertiroidismo], no especificada'),
  ('E28.2', 'Síndrome de ovario poliquístico'),
  ('E78.5', 'Hiperlipidemia, no especificada'),
  ('E55.9', 'Deficiencia de vitamina D, no especificada'),
  ('E86', 'Depleción del volumen (deshidratación)'),
  ('D64.9', 'Anemia, no especificada'),
  -- Respiratorio
  ('J03.9', 'Amigdalitis aguda, no especificada'),
  ('J06.9', 'Infección aguda de las vías respiratorias superiores, no especificada'),
  ('J20.9', 'Bronquitis aguda, no especificada'),
  ('J45.9', 'Asma, no especificada'),
  ('J18.9', 'Neumonía, organismo no especificado'),
  -- Digestivo
  ('K21.9', 'Enfermedad del reflujo gastroesofágico sin esofagitis'),
  ('K29.7', 'Gastritis, no especificada'),
  ('K52.9', 'Colitis y gastroenteritis no infecciosas, no especificadas'),
  ('K59.0', 'Estreñimiento'),
  ('R11', 'Náusea y vómito'),
  -- Síntomas y signos generales
  ('R50.9', 'Fiebre, no especificada'),
  ('R05', 'Tos'),
  ('R42', 'Mareo y desvanecimiento'),
  ('R53', 'Malestar y fatiga'),
  ('R60.9', 'Edema, no especificado'),
  ('R63.4', 'Pérdida anormal de peso'),
  ('G43.9', 'Migraña, no especificada'),
  -- Musculoesquelético
  ('M54.2', 'Cervicalgia'),
  ('M25.5', 'Dolor en articulación'),
  ('M79.1', 'Mialgia'),
  -- Piel
  ('L30.9', 'Dermatitis, no especificada'),
  ('L23.9', 'Dermatitis alérgica de contacto, de causa no especificada'),
  ('L50.9', 'Urticaria, no especificada'),
  ('B35.9', 'Dermatofitosis, no especificada (tiña)'),
  -- Salud mental
  ('F43.2', 'Trastornos de adaptación'),
  ('F51.0', 'Insomnio no orgánico'),
  -- Pediatría / general
  ('Z00.1', 'Control de salud de rutina del niño'),
  ('J21.9', 'Bronquiolitis aguda, no especificada'),
  ('B34.9', 'Infección viral, no especificada'),
  ('H66.9', 'Otitis media, no especificada')
ON CONFLICT ("codigo") DO NOTHING;
